### ISSUE TITLE
Нет доступа к коллекции playedTime

### ISSUE THREAD

**Issue by Boolgakova** [Boolgakova/JavaQACommandProject#1]
# Описание
Невозможно обращение к коллекции playedTime в классе Player.

# Локация дефекта
https://github.com/Boolgakova/JavaQACommandProject/blob/064fe3b1956e7277ee69756b524fd942dce87762/src/main/java/ru/netology/Player.java#L12

#Шаги воспроизведения

1. Открыть [код программы / ветка player](https://github.com/Boolgakova/JavaQACommandProject/tree/player) в IDEA
1. Запустить тест shouldInstallNewGame из [класса PlayerTest](https://github.com/Boolgakova/JavaQACommandProject/blob/player/src/test/java/ru/netology/PlayerTest.java)
1. Посмотреть на вывод в консоли

*Ожидаемый результат*: Тест проходит.
*Фактический результат*: Тест не проходит. Сообщение в консоли: java: playedTime has private access in ru.netology.Player

Воспроизводится также для тестов: 
* shouldNotFindNotInstalledGame, 
* shouldNothingHappenWhenInstallExistingGame, 
* shouldSumTimeOfNewGame, 
* shouldSumTimeOfOldGame.

# Скриншот
![image](https://user-images.githubusercontent.com/104353048/179343323-2c91e3f1-0166-41d5-b527-ce695dfee197.png)
![image](https://user-images.githubusercontent.com/104353048/179343340-b2be0e51-4dac-4b73-b8c5-c5bb3014dd94.png)

# Окружение
* **Операционная система**: macOS Catalina версия: 10.15.7
* **IDE**: IntelliJ IDEA 2022.1.1 (Community Edition), Build #IC-221.5591.52, built on May 10, 2022
* **Java**: corretto - 11.0.15

**Comment by Ksenya31** [comment]
close as completed
