### ISSUE TITLE
Метод mostPlayerByGenre возвращает тип значения, отличный от ТЗ

### ISSUE THREAD

**Issue by Boolgakova** [Boolgakova/JavaQACommandProject#11]
# Описание
В соответствии с описанием метод mostPlayerByGenre должен возвращать игру (тип Game). В соответствии с этим требованием написаны и тесты. А он сейчас возвращает значение типа String.

# Локация дефекта
https://github.com/Boolgakova/JavaQACommandProject/blob/fc03248b866064bc445cb9dfc7ace4f26e260384/src/main/java/ru/netology/Player.java#L56-L66

#Шаги воспроизведения

1. Открыть [код программы / ветку player](https://github.com/Boolgakova/JavaQACommandProject/tree/player/) в IDEA
1. Запустить тест shouldShowMostPlayedGame из класса [PlayerTest](https://github.com/Boolgakova/JavaQACommandProject/blob/player/src/test/java/ru/netology/PlayerTest.java)
1. Посмотреть на вывод в консоли

*Ожидаемый результат*: Тест проходит. 
*Фактический результат*: Тест не проходит. Java подчеркивает красным actual, обращая внимание на то, что мы ожидаем тип данных Game, а метод выдает String.

Также воспроизводится для теста shouldNullIfNotPlayThisGenre.

# Скриншот
![image](https://user-images.githubusercontent.com/104353048/179672665-09ad39ad-7d91-4b81-9d51-9bdaca6132a4.png)
![image](https://user-images.githubusercontent.com/104353048/179672809-fab4d3d0-27c5-4b32-8963-8d3aaff30a32.png)

# Окружение
* **Операционная система**: macOS Catalina версия: 10.15.7
* **IDE**: IntelliJ IDEA 2022.1.1 (Community Edition), Build #IC-221.5591.52, built on May 10, 2022
* **Java**: corretto - 11.0.15

**Comment by Ksenya31** [comment]
leave a comment
