### ISSUE TITLE
Время игры в игру не суммируется

### ISSUE THREAD

**Issue by Boolgakova** [Boolgakova/JavaQACommandProject#2]
# Описание
Метод play не добавляет время, которое игрок играл в игру, в коллекцию playedTime.

# Локация дефекта
https://github.com/Boolgakova/JavaQACommandProject/blob/064fe3b1956e7277ee69756b524fd942dce87762/src/main/java/ru/netology/Player.java#L33-L41

#Шаги воспроизведения

1. Открыть [код программы / ветку player](https://github.com/Boolgakova/JavaQACommandProject/tree/player/) в IDEA
1. Запустить тест shouldSumTimeOfNewGame из класса [PlayerTest](https://github.com/Boolgakova/JavaQACommandProject/blob/player/src/test/java/ru/netology/PlayerTest.java)
1. Посмотреть на вывод в консоли

*Ожидаемый результат*: Тест проходит. 
*Фактический результат*: Тест не проходит. Сообщение в консоли о несоответствии ожидаемого результата фактическому.

Также воспроизводится для теста shouldSumTimeOfOldGame.

# Скриншот
![image](https://user-images.githubusercontent.com/104353048/179343796-4545ae9e-e8ee-462b-932f-2fd72f3a302b.png)

# Окружение
* **Операционная система**: macOS Catalina версия: 10.15.7
* **IDE**: IntelliJ IDEA 2022.1.1 (Community Edition), Build #IC-221.5591.52, built on May 10, 2022
* **Java**: corretto - 11.0.15

**Comment by Ksenya31** [comment]
close as completed

**Comment by Ksenya31** [comment]
close as completed
