### ISSUE TITLE
Отсутствует выброс исключения RuntimeException

### ISSUE THREAD

**Issue by Boolgakova** [Boolgakova/JavaQACommandProject#3]
# Описание
В методе play не предусмотрен выброс исключения RuntimeException, если игра не была установлена, как то предписано в документации (описании к методу). Вместо этого код метода предполагает добавление неустановленной игры и времени игры в коллекцию playedTime.

# Локация дефекта
https://github.com/Boolgakova/JavaQACommandProject/blob/064fe3b1956e7277ee69756b524fd942dce87762/src/main/java/ru/netology/Player.java#L33-L41

#Шаги воспроизведения

1. Открыть [код программы / ветку player](https://github.com/Boolgakova/JavaQACommandProject/tree/player/) в IDEA
1. Запустить тест shouldThrowRuntimeExceptionWhenGameNotInstall из класса [PlayerTest](https://github.com/Boolgakova/JavaQACommandProject/blob/player/src/test/java/ru/netology/PlayerTest.java)
1. Посмотреть на вывод в консоли

*Ожидаемый результат*: Тест проходит. 
*Фактический результат*: Тест не проходит. Сообщение в консоли: org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
![image](https://user-images.githubusercontent.com/104353048/179344199-c28ab617-dc68-4869-a314-d329205a32c1.png)

# Окружение
* **Операционная система**: macOS Catalina версия: 10.15.7
* **IDE**: IntelliJ IDEA 2022.1.1 (Community Edition), Build #IC-221.5591.52, built on May 10, 2022
* **Java**: corretto - 11.0.15

**Comment by Ksenya31** [comment]
close as completed
