### ISSUE TITLE
Метод sumGenre не суммирует время игры в игры заданного жанра

### ISSUE THREAD

**Issue by Boolgakova** [Boolgakova/JavaQACommandProject#4]
# Описание
Метод sumGenre не суммирует время игры в игры заданного жанра в связи с зависимостью от метода play. Для суммирования игрового времени игры заданного жанра метод sumGenre обращается к коллекции playedTime, в которую с помощью метода play должны быть добавлены игры и время игры в них. Но так как в методе play содержится дефект (Issue #2) метод sumGenre также не работает.

# Локация дефекта
https://github.com/Boolgakova/JavaQACommandProject/blob/064fe3b1956e7277ee69756b524fd942dce87762/src/main/java/ru/netology/Player.java#L45-L55

https://github.com/Boolgakova/JavaQACommandProject/blob/064fe3b1956e7277ee69756b524fd942dce87762/src/main/java/ru/netology/Player.java#L33-L41

#Шаги воспроизведения

1. Открыть [код программы / ветку player](https://github.com/Boolgakova/JavaQACommandProject/tree/player/) в IDEA
1. Запустить тест shouldSumGenreIfOneGame из класса [PlayerTest](https://github.com/Boolgakova/JavaQACommandProject/blob/player/src/test/java/ru/netology/PlayerTest.java)
1. Посмотреть на вывод в консоли

*Ожидаемый результат*: Тест проходит. 
*Фактический результат*: Тест не проходит. Сообщение в консоли о несоответствии ожидаемого результата фактическому.

Также воспроизводится для тестов:
* shouldSumGenreInSeveralGames,
* shouldNotSumDifferentGenre,
* shouldSumGenreInSeveralGamesWithRepeat,
* shouldNotSumGenreOfDifferentPlayer.

# Скриншот
![image](https://user-images.githubusercontent.com/104353048/179345050-8c4c41aa-c1c4-40b2-85f5-af50c4de6676.png)
![image](https://user-images.githubusercontent.com/104353048/179345066-1e2f418a-4904-43d7-8722-72f921e5e71b.png)

# Окружение
* **Операционная система**: macOS Catalina версия: 10.15.7
* **IDE**: IntelliJ IDEA 2022.1.1 (Community Edition), Build #IC-221.5591.52, built on May 10, 2022
* **Java**: corretto - 11.0.15

**Comment by Ksenya31** [comment]
close as completed
