### ISSUE TITLE
Метод sumGenre обнуляет результат суммирования при переборе

### ISSUE THREAD

**Issue by Boolgakova** [Boolgakova/JavaQACommandProject#5]
# Описание
В коде метода sumGenre содержится ошибка, из-за которой при переборе коллекции playedTime и сравнении жанра с заданным в параметре, если жанр совпадает с заданным, время игры суммируется, но если попадается игра с другим жанром, сумма обнуляется (else {sum = 0;}) и время следующих игр суммируется уже с нулем. 

# Локация дефекта
https://github.com/Boolgakova/JavaQACommandProject/blob/064fe3b1956e7277ee69756b524fd942dce87762/src/main/java/ru/netology/Player.java#L45-L55

#Шаги воспроизведения

1. Открыть [код программы / ветку player](https://github.com/Boolgakova/JavaQACommandProject/tree/player/) в IDEA
1. Запустить тест shouldNotSumDifferentGenre из класса [PlayerTest](https://github.com/Boolgakova/JavaQACommandProject/blob/player/src/test/java/ru/netology/PlayerTest.java)
1. Посмотреть на вывод в консоли

*Ожидаемый результат*: Тест проходит. 
*Фактический результат*: Тест не проходит. Сообщение в консоли о несоответствии ожидаемого результата фактическому.

# Скриншот
![image](https://user-images.githubusercontent.com/104353048/179345959-f9f5f4d3-d86a-44a5-af0d-a25de1723b29.png)

# Окружение
* **Операционная система**: macOS Catalina версия: 10.15.7
* **IDE**: IntelliJ IDEA 2022.1.1 (Community Edition), Build #IC-221.5591.52, built on May 10, 2022
* **Java**: corretto - 11.0.15

**Comment by Ksenya31** [comment]
close as completed
