### ISSUE TITLE
Метод mostPlayerByGenre всегда возвращает null

### ISSUE THREAD

**Issue by Boolgakova** [Boolgakova/JavaQACommandProject#6]
# Описание
Метод mostPlayerByGenre всегда возвращает null. В теле метода нет никаких условий кроме возвращения null.

# Локация дефекта
https://github.com/Boolgakova/JavaQACommandProject/blob/064fe3b1956e7277ee69756b524fd942dce87762/src/main/java/ru/netology/Player.java#L59-L61

#Шаги воспроизведения

1. Открыть [код программы / ветку player](https://github.com/Boolgakova/JavaQACommandProject/tree/player/) в IDEA
1. Запустить тест shouldShowMostPlayedGame из класса [PlayerTest](https://github.com/Boolgakova/JavaQACommandProject/blob/player/src/test/java/ru/netology/PlayerTest.java)
1. Посмотреть на вывод в консоли

*Ожидаемый результат*: Тест проходит. 
*Фактический результат*: Тест не проходит. Сообщение в консоли о несоответствии ожидаемого результата (game) фактическому (null).

# Скриншот
![image](https://user-images.githubusercontent.com/104353048/179346315-bce20dee-81c7-40bc-b630-05ca2290c738.png)

# Окружение
* **Операционная система**: macOS Catalina версия: 10.15.7
* **IDE**: IntelliJ IDEA 2022.1.1 (Community Edition), Build #IC-221.5591.52, built on May 10, 2022
* **Java**: corretto - 11.0.15

**Comment by Ksenya31** [comment]
В тестах shouldShowMostPlayedGame и shouldNullIfNotPlayThisGenre неверно указан параметр Game actual = player.mostPlayerByGenre не давал запускать тесты, исправила по подсказке на  String actual = player.mostPlayerByGenre все тесты проходят успешно
