### ISSUE TITLE
Метод getMostPlayer, в классе Gamestore, не принимает значение времени равным = 1.

### ISSUE THREAD

**Issue by Ksenya31** [Boolgakova/JavaQACommandProject#9]
# Описание
Метод getMostPlayer, в классе Gamestore, не принимает значение времени равным = 1.

# Локализация дефекта
https://github.com/Boolgakova/JavaQACommandProject/blob/6b5ce10e943ae310b2d28c10beafbcc1df94753a/src/main/java/ru/netology/GameStore.java#L58-L68

#Шаги воспризведения
1. Открыть [код программы/ветку gamestore](https://github.com/Boolgakova/JavaQACommandProject/tree/gamestore/)
2. Запустить тест MostPlayerEqualsZero из класса [GameStoreTest](https://github.com/Boolgakova/JavaQACommandProject/blob/player/src/test/java/ru/netology/GameStoreTest.java)
3. Посмотреть на результат теста в консоли

*Ожидаемый результат:* Результат теста - "Alena", время добавилось, метод getMostPlayer вернул значение имени игрока.
*Фактический результат:* Результат теста - null, Метод getMostPlayer не нашел игрока со временем равным 1 час.

# Скриншот
![getMostPlayer](https://user-images.githubusercontent.com/104645992/179454620-5fba76bc-460e-4e24-9024-e6a709872104.png)

* **Операционная система:** Windows 7
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** java 11 11.0.14

**Comment by Boolgakova** [comment]
Закрывается, как не требующий исправления из-за ошибки в тесте.
